// Archivo: lib/data/default_units.dart
import 'package:agro_listados/models/product.dart';
const Map<String, UnitType> defaultUnits = {
  "Apio": UnitType.Caja,
  "Ajo": UnitType.Caja,
  "Ayote": UnitType.Bolsa,
  "Brocoli Sencillo": UnitType.Bolsa,
  "Berenjena": UnitType.Bolsa,
  "Cebolla Blanca": UnitType.Saco,
  "Cebolla Morada": UnitType.Saco,
  "Coliflor": UnitType.Bulto,
  "Chile Verde": UnitType.Saco,
  "Ejotes": UnitType.Saco,
  "Elote Dulce": UnitType.Fardo,
  "Guisquil Chapin": UnitType.Saco,
  "Guisquil Indio Primera": UnitType.Bolsa,
  "Chile Jalapeño": UnitType.Saco,
  "Lechuga Grande": UnitType.Caja,
  "Lechuga Mediana": UnitType.Caja,
  "Limon": UnitType.Saco,
  "Papa Bellina": UnitType.Quintal,
  "Pepino": UnitType.Saco,
  "Platano Grande": UnitType.Caja,
  "Pipian de Primera": UnitType.Ciento,
  "Pipian de Segunda": UnitType.Ciento,
  "Remolacha": UnitType.Bulto,
  "Repollo": UnitType.Bulto,
  "Tomate Grueso": UnitType.Caja,
  "Tomate Mediano": UnitType.Caja,
  "Zanahoria Grande sin Tallo": UnitType.Saco,
  "Zucchini": UnitType.Bolsa,
  "Yuca": UnitType.Saco,
  "Banano": UnitType.Caja,
  "Lichas": UnitType.Bolsa,
  "Jamaica": UnitType.Unidad,
  "Manzana Gala": UnitType.Caja,
  "Manzana Verde": UnitType.Caja,
  "Naranja": UnitType.Saco,
  "Papa Grande": UnitType.Saco,
  "Piña": UnitType.Caja,
  "Rabano": UnitType.Bolsa,
  "Aguacate Indio": UnitType.Caja,
  "Aguacate Mexicano": UnitType.Caja,
  "Alberja China": UnitType.Bolsa,
  "Arándanos": UnitType.Caja,
  "Berro": UnitType.Manojo,
  "Camote": UnitType.Saco,
  "Chipilin": UnitType.Manojo,
  "Chocolate": UnitType.Unidad,
  "Cilantro": UnitType.Manojo,
  "Coco": UnitType.Unidad,
  "Elote": UnitType.Saco,
  "Fresa": UnitType.Bandeja,
  "Fruta en Bandeja": UnitType.Bandeja,
  "Gelatinitas": UnitType.Caja,
  "Gomitas": UnitType.Caja,
  "Granadilla": UnitType.Bolsa,
  "Guineo de Seda": UnitType.Caja,
  "Kiwi": UnitType.Caja,
  "Mamey": UnitType.Bolsa,
  "Mandarina Clementina": UnitType.Caja,
  "Mandarina": UnitType.Bolsa,
  "Manzana Mixta": UnitType.Caja,
  "Manzana Golden": UnitType.Caja,
  "Melon": UnitType.Unidad,
  "Melocotón": UnitType.Caja,
  "Mora (Fruta)": UnitType.Caja,
  "Mora Monte": UnitType.Manojo,
  "Nance": UnitType.Bolsa,
  "Tamarindo": UnitType.Libra,
  "Platano Mediano": UnitType.Caja,
  "Manzana Roja": UnitType.Caja,
  "Maracuyá": UnitType.Bolsa,
  "Brocoli Doble": UnitType.Bolsa,
  "Brocoli Pequeño": UnitType.Bolsa,
  "Anona": UnitType.Jaba,
  "Encurtido o Curtido": UnitType.Unidad,
  "Ciruela": UnitType.Caja,
  "Dulce de Panela": UnitType.Unidad,
  "Espinaca": UnitType.Manojo,
  "Guisquil Perulero": UnitType.Saco,
  "Hierbabuena": UnitType.Manojo,
  "Huevo Grande": UnitType.Caja,
  "Huevo Mediano": UnitType.Caja,
  "Huevos Extra Grandes": UnitType.Caja,
  "Huevos Pequeños": UnitType.Caja,
  "Jicama": UnitType.Bolsa,
  "Jocote": UnitType.Bolsa,
  "Jocote Acido": UnitType.Bolsa,
  "Jocote de Azucaron": UnitType.Bolsa,
  "Lechuga Escarola": UnitType.Caja,
  "Loroco": UnitType.Caja,
  "Manzana Pink Lady": UnitType.Caja,
  "Marshmallow": UnitType.Caja,
  "Olor": UnitType.Manojo,
  "Papa Mexicana": UnitType.Saco,
  "Papa Pequeña en Red": UnitType.Saco,
  "Papa Russet": UnitType.Saco,
  "Papa Soloma": UnitType.Saco,
  "Papaya": UnitType.Caja,
  "Pera": UnitType.Caja,
  "Perejil": UnitType.Manojo,
  "Repollo Morado": UnitType.Bulto,
  "Sandia": UnitType.Unidad,
  "Mix de Monte": UnitType.Bolsa,
  "Tomate de Tercera": UnitType.Caja,
  "Uva Morada": UnitType.Caja,
  "Uva Negra": UnitType.Caja,
  "Uva Roja": UnitType.Caja,
  "Uva Verde": UnitType.Caja,
  "Zanahoria Pequeña sin Tallo": UnitType.Saco,
  "Cebolla amarilla":UnitType.Saco,
  "Chile morrón":UnitType.Bandeja,
  "Mango":UnitType.Bolsa,
  "Cebollines":UnitType.Bulto,
  "Guisquil indio de primera":UnitType.Bolsa,
  "Guisquil indio de segunda":UnitType.Bolsa,
};