// Archivo: lib/data/default_units.dart

import '../models/product.dart';

const Map<String, UnitType> defaultUnits = {
  "Apio": UnitType.Caja,
  "Ajo": UnitType.Caja,
  "Ayote": UnitType.Bolsa,
  "Brócoli Sencillo": UnitType.Bolsa,
  "Berenjena": UnitType.Bolsa,
  "Cebolla Blanca": UnitType.Saco,
  "Cebolla Morada": UnitType.Saco,
  "Coliflor": UnitType.Bulto,
  "Chile Verde": UnitType.Saco,
  "Ejotes": UnitType.Saco,
  "Elote Dulce": UnitType.Fardo,
  "Güisquil Chapín": UnitType.Saco,
  "Güisquil Indio Primera": UnitType.Bolsa,
  "Chile Jalapeño": UnitType.Saco,
  "Lechuga Grande": UnitType.Caja,
  "Lechuga Mediana": UnitType.Caja,
  "Limón": UnitType.Saco,
  "Papa Bellina": UnitType.Quintal,
  "Pepino": UnitType.Saco,
  "Plátano Grande": UnitType.Caja,
  "Pipian de Primera": UnitType.Ciento,
  "Pipian de Segunda": UnitType.Ciento,
  "Remolacha": UnitType.Bulto,
  "Repollo": UnitType.Bulto,
  "Tomate Grueso": UnitType.Caja,
  "Tomate Mediano": UnitType.Caja,
  "Zanahoria Grande sin Tallo": UnitType.Saco,
  "Zucchini": UnitType.Bolsa,
  "Yuca": UnitType.Saco,
  "Banano": UnitType.Caja,
  "Lichas": UnitType.Bolsa,
  "Jamaica": UnitType.Unidad,
  "Manzana Gala": UnitType.Caja,
  "Manzana Verde": UnitType.Caja,
  "Naranja": UnitType.Saco,
  "Papa Grande": UnitType.Saco,
  "Piña": UnitType.Caja,
  "Rábano": UnitType.Bolsa,
  "Aguacate Indio": UnitType.Caja,
  "Aguacate Mexicano": UnitType.Caja,
  "Alberja China": UnitType.Bolsa,
  "Arándanos": UnitType.Caja,
  "Berro": UnitType.Manojo,
  "Camote": UnitType.Saco,
  "Chipilín": UnitType.Manojo,
  "Chocolate": UnitType.Unidad,
  "Cilantro": UnitType.Manojo,
  "Coco": UnitType.Unidad,
  "Elote": UnitType.Saco,
  "Fresa": UnitType.Bandeja,
  "Fruta en Bandeja": UnitType.Bandeja,
  "Gelatinitas": UnitType.Caja,
  "Gomitas": UnitType.Caja,
  "Granadilla": UnitType.Bolsa,
  "Guineo de Seda": UnitType.Caja,
  "Kiwi": UnitType.Caja,
  "Mamey": UnitType.Bolsa,
  "Mandarina Clementina": UnitType.Caja,
  "Mandarina": UnitType.Bolsa,
  "Manzana Mixta": UnitType.Caja,
  "Manzana Golden": UnitType.Caja,
  "Melón": UnitType.Unidad,
  "Melocotón": UnitType.Caja,
  "Mora (Fruta)": UnitType.Caja,
  "Mora Monte": UnitType.Manojo,
  "Nance": UnitType.Bolsa,
  "Tamarindo": UnitType.Libra,
  "Plátano Mediano": UnitType.Caja,
  "Manzana Roja": UnitType.Caja,
  "Maracuyá": UnitType.Bolsa,
  "Brócoli Doble": UnitType.Bolsa,
  "Brócoli Pequeño": UnitType.Bolsa,
  "Anona": UnitType.Jaba,
  "Encurtido o Curtido": UnitType.Unidad,
  "Ciruela": UnitType.Caja,
  "Dulce de Panela": UnitType.Unidad,
  "Espinaca": UnitType.Manojo,
  "Güisquil Perulero": UnitType.Saco,
  "Hierbabuena": UnitType.Manojo,
  "Huevo Grande": UnitType.Caja,
  "Huevo Mediano": UnitType.Caja,
  "Huevos Extra Grandes": UnitType.Caja,
  "Huevos Pequeños": UnitType.Caja,
  "Jícama": UnitType.Bolsa,
  "Jocote": UnitType.Bolsa,
  "Jocote Ácido": UnitType.Bolsa,
  "Jocote de Azúcarón": UnitType.Bolsa,
  "Lechuga Escarola": UnitType.Caja,
  "Loroco": UnitType.Caja,
  "Manzana Pink Lady": UnitType.Caja,
  "Marshmallow": UnitType.Caja,
  "Olor": UnitType.Manojo,
  "Papa Mexicana": UnitType.Saco,
  "Papa Pequeña en Red": UnitType.Saco,
  "Papa Russet": UnitType.Saco,
  "Papa Soloma": UnitType.Saco,
  "Papaya": UnitType.Caja,
  "Pera": UnitType.Caja,
  "Perejil": UnitType.Manojo,
  "Repollo Morado": UnitType.Bulto,
  "Sandía": UnitType.Unidad,
  "Mix de Monte": UnitType.Bolsa,
  "Tomate de Tercera": UnitType.Caja,
  "Uva Morada": UnitType.Caja,
  "Uva Negra": UnitType.Caja,
  "Uva Roja": UnitType.Caja,
  "Uva Verde": UnitType.Caja,
  "Zanahoria Pequeña sin Tallo": UnitType.Saco,
};